(()=>{
if(typeof lessons==='undefined'||typeof tests==='undefined')return;
const groups=[
['Lớp 1–5',[['Pre-A1','Classroom','Đồ vật lớp học','pencil:bút chì,book:sách,ruler:thước,desk:bàn'],['Pre-A1','Animals','Động vật','cat:mèo,dog:chó,bird:chim,fish:cá'],['A1','Food','Đồ ăn','rice:cơm,milk:sữa,apple:táo,water:nước'],['A1','My body','Cơ thể','head:đầu,hand:bàn tay,eye:mắt,foot:bàn chân'],['A1','Weather','Thời tiết','sunny:nắng,rainy:mưa,cloudy:nhiều mây,windy:có gió'],['A1','Clothes','Quần áo','shirt:áo sơ mi,dress:váy,shoes:giày,hat:mũ'],['A1–A2','My home','Ngôi nhà','kitchen:bếp,bedroom:phòng ngủ,bathroom:phòng tắm,garden:vườn'],['A2','Hobbies','Sở thích','draw:vẽ,dance:nhảy,collect:sưu tầm,cycle:đạp xe'],['A2','Around town','Thành phố','library:thư viện,hospital:bệnh viện,market:chợ,park:công viên']]],
['Lớp 6–9',[['A2','Past events','Sự kiện quá khứ','visited:đã thăm,watched:đã xem,went:đã đi,saw:đã thấy'],['A2','Actions now','Hành động hiện tại','studying:đang học,cooking:đang nấu,playing:đang chơi,waiting:đang đợi'],['A2','Comparisons','So sánh','taller:cao hơn,faster:nhanh hơn,stronger:khỏe hơn,better:tốt hơn'],['A2–B1','Advice','Lời khuyên','should:nên,must:phải,might:có thể,could:có thể'],['B1','Future plans','Kế hoạch','plan:kế hoạch,arrange:sắp xếp,schedule:lịch trình,predict:dự đoán'],['B1','Experiences','Trải nghiệm','ever:từng,never:chưa bao giờ,already:đã rồi,yet:chưa'],['B1','Connecting ideas','Nối ý','who:người mà,which:vật mà,where:nơi mà,whose:của ai'],['B1','Conditions','Điều kiện','if:nếu,unless:trừ khi,result:kết quả,condition:điều kiện'],['B1','Email writing','Viết email','subject:tiêu đề,greeting:lời chào,request:yêu cầu,regards:trân trọng']]],
['Lớp 10–12',[['B1','Listening keywords','Từ khóa nghe','predict:dự đoán,distractor:nhiễu,spelling:chính tả,plural:số nhiều'],['B1–B2','Reading evidence','Bằng chứng đọc','claim:nhận định,evidence:bằng chứng,contradict:mâu thuẫn,mention:đề cập'],['B2','Matching headings','Ghép tiêu đề','idea:ý chính,detail:chi tiết,heading:tiêu đề,scope:phạm vi'],['B2','Chart trends','Xu hướng biểu đồ','increase:tăng,decline:giảm,stable:ổn định,peak:đạt đỉnh'],['B2','Task 1 overview','Tổng quan Task 1','overall:nhìn chung,feature:đặc điểm,contrast:tương phản,exception:ngoại lệ'],['B2','Opinion essay','Bài luận quan điểm','position:lập trường,support:hỗ trợ,example:ví dụ,conclude:kết luận'],['B1–B2','Speaking Part 1','Nói Part 1','direct:trực tiếp,reason:lý do,detail:chi tiết,natural:tự nhiên'],['B2','Speaking Part 2','Nói Part 2','topic:chủ đề,structure:cấu trúc,sequence:trình tự,extend:phát triển'],['B2','Pronunciation','Phát âm','stress:trọng âm,rhythm:nhịp,chunk:cụm ý,intonation:ngữ điệu']]],
['Đại học',[['B2–C1','Academic collocations','Cụm học thuật','research:nghiên cứu,challenge:thách thức,conclusion:kết luận,consensus:đồng thuận'],['C1','Hedging','Ngôn ngữ thận trọng','suggest:gợi ý,appear:có vẻ,may:có thể,tend:có xu hướng'],['C1','Nominalisation','Danh hóa','analyse:phân tích,analysis:sự phân tích,decide:quyết định,decision:sự quyết định'],['B2–C1','Academic passive','Bị động học thuật','measure:đo,select:chọn,define:định nghĩa,observe:quan sát'],['C1','Synthesising','Tổng hợp nguồn','source:nguồn,compare:so sánh,integrate:tích hợp,theme:chủ đề'],['C1','Referencing','Trích dẫn','cite:trích dẫn,paraphrase:diễn đạt lại,plagiarism:đạo văn,quotation:trích trực tiếp'],['C1','Presentations','Thuyết trình','outline:dàn ý,transition:chuyển ý,emphasise:nhấn mạnh,summarise:tóm tắt'],['C1','Seminars','Thảo luận','clarify:làm rõ,challenge:phản biện,respond:phản hồi,consensus:đồng thuận'],['C1–C2','IELTS criteria','Tiêu chí IELTS','fluency:trôi chảy,cohesion:liên kết,lexical:vốn từ,accuracy:chính xác']]]
];
groups.forEach((g,gi)=>g[1].forEach((t,i)=>{const w=t[3].split(',').map(x=>x.split(':'));const words=w.map(x=>x[0]+'|'+x[1]+'|This topic practises the word “'+x[0]+'”.');lessons.push(['extra-'+gi+'-'+i,g[0],t[0],t[1],t[2],words,'Học từ trong ngữ cảnh, nghe phát âm và ôn lại bằng nhiều dạng câu hỏi.',w[0][0]+' nghĩa là gì?|'+w[0][1]+','+w[1][1]+','+w[2][1]+'|0|'+w[0][0]+' nghĩa là '+w[0][1]+'.'])}));
tests.push(
['There ___ two books.','is,are,am',1,'Số nhiều dùng are.'],['I have ___ apple.','a,an,the',1,'Apple bắt đầu bằng nguyên âm.'],['They ___ now.','play,are playing,played',1,'Now báo hiệu hiện tại tiếp diễn.'],['Yesterday we ___ a film.','watch,watched,watches',1,'Yesterday dùng quá khứ đơn.'],['This bag is ___ than mine.','heavy,heavier,heaviest',1,'So sánh hơn là heavier.'],['You should ___ earlier.','sleep,sleeps,slept',0,'Sau should dùng nguyên mẫu.'],['I have never ___ sushi.','try,tried,trying',1,'Have + V3.'],['The girl ___ won is here.','which,who,where',1,'Who thay cho người.'],['If it rains, we ___ home.','stay,will stay,would stay',1,'Điều kiện loại 1 dùng will.'],['The room ___ daily.','cleans,is cleaned,cleaned',1,'Câu bị động dùng is cleaned.'],['I wish I ___ more time.','have,had,will have',1,'Wish hiện tại dùng quá khứ.'],['By 8, she ___ the report.','finished,had finished,finishes',1,'Past perfect: had finished.'],['Hardly ___ we arrived.','did,had,have',1,'Hardly had là cấu trúc đảo ngữ.'],['The data ___ a trend.','indicate,indicates,indicating',0,'Data thường dùng như số nhiều.'],['Sales fell; ___, costs rose.','for example,however,therefore',1,'However chỉ tương phản.'],['Substantial gần nghĩa?','minor,considerable,unclear',1,'Substantial gần nghĩa considerable.'],['If I ___ earlier, I would have caught it.','left,had left,would leave',1,'Điều kiện loại 3 dùng had + V3.'],['The policy ___ be effective.','may,is always,must always',0,'May là hedging.'],['IELTS overview cần?','Mọi số,Key trends,Ý kiến',1,'Overview nêu xu hướng chính.'],['Speaking fluency là?','Nói nhanh,Nói liên tục và mạch lạc,Chỉ từ hiếm',1,'Fluency là độ liên tục và mạch lạc.'],['Draw a conclusion là?','Collocation,Pronoun,Tense',0,'Đây là collocation.'],['Samples ___ carefully.','tested,were tested,testing',1,'Samples nhận hành động.'],['Paraphrase ___ citation.','never needs,still needs,replaces',1,'Paraphrase vẫn cần dẫn nguồn.'],['Band cao cần?','Chỉ từ khó,Diễn đạt chính xác,Không chia đoạn',1,'Điểm cao cần kiểm soát toàn diện.'],['Had it not rained, we ___ the match.','would finish,would have finished,finished',1,'Điều kiện loại 3: would have + V3.']
);
document.querySelector('#learn .lead').textContent=lessons.length+' bài; mỗi bài có flashcard, kiến thức và 4 câu luyện tập.';
let exIndex=0;
function makeEx(l){const b=l[7].split('|'),o=b[1].split(','),w=l[5].map(x=>x.split('|'));return[{q:b[0],o:o,a:+b[2],why:b[3]},{q:'“'+w[1][0]+'” nghĩa là?',o:[w[2][1],w[1][1],w[0][1]],a:1,why:w[1][0]+' nghĩa là '+w[1][1]+'.'},{q:'Từ nào nghĩa là “'+w[3][1]+'”?',o:[w[1][0],w[2][0],w[3][0]],a:2,why:'Đáp án là '+w[3][0]+'.'},{q:'“'+w[2][0]+'” thuộc chủ đề nào?',o:[l[3],'Một chủ đề khác','Không thuộc bài'],a:0,why:'Từ này nằm trong bài '+l[3]+'.'}]}
openLesson=function(id){current=lessons.find(l=>l[0]===id);wi=0;exIndex=0;drawLesson();show('lesson')};
drawLesson=function(){const w=current[5][wi].split('|'),e=makeEx(current)[exIndex];document.getElementById('lessonContent').innerHTML='<p class="eyebrow">'+current[1]+' · '+current[2]+'</p><h1>'+current[3]+'</h1><p class="lead">'+current[4]+'</p><div class="study"><div class="flash"><span class="eyebrow">FLASHCARD '+(wi+1)+'/4</span><div class="word"><div><strong>'+w[0]+'</strong><b>'+w[1]+'</b><p>'+w[2]+'</p></div></div><div class="controls"><button onclick="wi=(wi+3)%4;drawLesson()">←</button><button onclick="speak(&quot;'+w[0]+'&quot;)">🔊 Nghe</button><button onclick="wi=(wi+1)%4;drawLesson()">→</button></div></div><div class="note"><span class="eyebrow">GHI NHỚ</span><h2>Kiến thức trọng tâm</h2><p>'+current[6]+'</p></div></div><div class="quiz"><span class="eyebrow">LUYỆN TẬP '+(exIndex+1)+'/4</span><h2>'+e.q+'</h2><div class="options">'+e.o.map((x,i)=>'<button onclick="expandedAnswer(this,'+i+')">'+String.fromCharCode(65+i)+'. '+x+'</button>').join('')+'</div><div id="feedback"></div></div>'};
window.expandedAnswer=(el,i)=>{const e=makeEx(current)[exIndex],bs=[...el.parentElement.children];bs.forEach((b,n)=>{if(n===e.a)b.classList.add('correct');else if(n===i)b.classList.add('wrong');b.disabled=true});document.getElementById('feedback').innerHTML='<div class="result"><h3>'+(i===e.a?'✓ Chính xác':'✕ Chưa đúng')+'</h3><p>'+e.why+'</p>'+(exIndex<3?'<button class="btn primary" onclick="expandedNext()">Câu tiếp theo →</button>':'<button class="btn primary" onclick="completeAndNext()">Hoàn thành & bài tiếp theo →</button>')+'</div>'};
window.expandedNext=()=>{exIndex++;drawLesson()};
const baseComplete=completeAndNext;completeAndNext=function(){exIndex=0;baseComplete()};
test=function(){const t=tests[ti],o=t[1].split(',');document.getElementById('testBox').innerHTML='<span class="eyebrow">CÂU '+(ti+1)+'/'+tests.length+'</span><h2>'+t[0]+'</h2><div class="options">'+o.map((x,i)=>'<button onclick="pickTest('+i+')">'+String.fromCharCode(65+i)+'. '+x+'</button>').join('')+'</div><div id="testFeedback"></div>'};
pickTest=function(i){if(testAnswers[ti]!==undefined)return;testAnswers[ti]=i;const t=tests[ti],a=t[2],o=t[1].split(','),bs=[...document.querySelectorAll('#testBox .options button')];bs.forEach((b,n)=>{if(n===a)b.classList.add('correct');else if(n===i)b.classList.add('wrong');b.disabled=true});document.getElementById('testFeedback').innerHTML='<div class="result"><h3>'+(i===a?'✓ Chính xác':'✕ Chưa đúng')+'</h3><p><b>Đáp án: '+String.fromCharCode(65+a)+'. '+o[a]+'</b></p><p>'+t[3]+'</p><button class="btn primary" onclick="nextTest()">'+(ti<tests.length-1?'Câu tiếp theo →':'Xem kết quả →')+'</button></div>'};nextTest=function(){ti++;if(ti<tests.length)test();else renderTestResult()};
renderTestResult=function(){const s=testAnswers.reduce((n,x,i)=>n+(x===tests[i][2]?1:0),0);document.getElementById('testBox').innerHTML='<h2>Kết quả '+s+'/'+tests.length+'</h2><div class="reviewList">'+tests.map((t,n)=>{const o=t[1].split(',');return '<article class="reviewItem '+(testAnswers[n]===t[2]?'ok':'no')+'"><h3>'+t[0]+'</h3><p>Bạn chọn: '+o[testAnswers[n]]+'</p><p>Đúng: '+o[t[2]]+'</p><p>'+t[3]+'</p></article>'}).join('')+'</div>'};
render();ti=0;testAnswers=[];test();

const randomize=a=>{const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x};
const makeChoice=(q,correct,wrong,why)=>{const o=randomize([correct,...wrong.slice(0,2)]);return{q:q,o:o,a:o.indexOf(correct),why:why}};
let activeExercises=[];
function lessonPool(l){
 const w=l[5].map(x=>x.split('|')),others=randomize(lessons.filter(x=>x[0]!==l[0]).flatMap(x=>x[5].map(y=>y.split('|'))));
 const pool=[];
 w.forEach((v,i)=>{
  const same=w.filter((_,n)=>n!==i);
  pool.push(makeChoice('“'+v[0]+'” nghĩa là gì?',v[1],same.map(x=>x[1]),v[0]+' nghĩa là '+v[1]+'.'));
  pool.push(makeChoice('Từ tiếng Anh của “'+v[1]+'” là gì?',v[0],same.map(x=>x[0]),'Đáp án đúng là '+v[0]+'.'));
  pool.push(makeChoice('Từ nào thuộc chủ đề “'+l[3]+'”?',v[0],others.slice(i*2,i*2+2).map(x=>x[0]),v[0]+' là từ trong bài '+l[3]+'.'));
  const typo1=v[0].length>3?v[0].slice(0,-1):v[0]+'e',typo2=v[0].length>2?v[0][0]+v[0].slice(2)+v[0][1]:v[0]+'s';
  pool.push(makeChoice('Chọn cách viết đúng của từ “'+v[1]+'”.',v[0],[typo1,typo2],v[0]+' là cách viết đúng.'));
 });
 return pool;
}
openLesson=function(id){current=lessons.find(l=>l[0]===id);wi=0;exIndex=0;activeExercises=randomize(lessonPool(current)).slice(0,4);drawLesson();show('lesson')};
drawLesson=function(){const w=current[5][wi].split('|'),e=activeExercises[exIndex];document.getElementById('lessonContent').innerHTML='<p class="eyebrow">'+current[1]+' · '+current[2]+'</p><h1>'+current[3]+'</h1><p class="lead">'+current[4]+'</p><div class="study"><div class="flash"><span class="eyebrow">FLASHCARD '+(wi+1)+'/4</span><div class="word"><div><strong>'+w[0]+'</strong><b>'+w[1]+'</b><p>'+w[2]+'</p></div></div><div class="controls"><button onclick="wi=(wi+3)%4;drawLesson()">←</button><button onclick="speak(&quot;'+w[0]+'&quot;)">🔊 Nghe</button><button onclick="wi=(wi+1)%4;drawLesson()">→</button></div></div><div class="note"><span class="eyebrow">GHI NHỚ</span><h2>Kiến thức trọng tâm</h2><p>'+current[6]+'</p><p><b>Ngân hàng:</b> '+lessonPool(current).length+' câu · lượt này chọn ngẫu nhiên 4 câu.</p></div></div><div class="quiz"><span class="eyebrow">LUYỆN TẬP NGẪU NHIÊN · '+(exIndex+1)+'/4</span><div class="meter"><i style="width:'+((exIndex+1)*25)+'%"></i></div><h2>'+e.q+'</h2><div class="options">'+e.o.map((x,i)=>'<button onclick="expandedAnswer(this,'+i+')">'+String.fromCharCode(65+i)+'. '+x+'</button>').join('')+'</div><div id="feedback"></div></div>'};
window.expandedAnswer=(el,i)=>{const e=activeExercises[exIndex],bs=[...el.parentElement.children];bs.forEach((b,n)=>{if(n===e.a)b.classList.add('correct');else if(n===i)b.classList.add('wrong');b.disabled=true});document.getElementById('feedback').innerHTML='<div class="result"><h3>'+(i===e.a?'✓ Chính xác':'✕ Chưa đúng')+'</h3><p><b>Đáp án: '+String.fromCharCode(65+e.a)+'. '+e.o[e.a]+'</b></p><p>'+e.why+'</p>'+(exIndex<3?'<button class="btn primary" onclick="expandedNext()">Câu tiếp theo →</button>':'<button class="btn primary" onclick="completeAndNext()">Hoàn thành & bài tiếp theo →</button>')+' <button class="btn soft" onclick="drawLesson()">Xem lại câu này</button></div>'};
const originalComplete=completeAndNext;completeAndNext=function(){const idx=lessons.findIndex(l=>l[0]===current[0]);saveDone();current=lessons[(idx+1)%lessons.length];wi=0;exIndex=0;activeExercises=randomize(lessonPool(current)).slice(0,4);drawLesson();scrollTo(0,0)};
const placementBank=[...tests];
lessons.forEach(l=>l[5].map(x=>x.split('|')).forEach((v,i,arr)=>{
 const other=arr.filter((_,n)=>n!==i);
 const q1=makeChoice('“'+v[0]+'” nghĩa là gì?',v[1],other.map(x=>x[1]),v[0]+' nghĩa là '+v[1]+'.');
 placementBank.push([q1.q,q1.o.join(','),q1.a,q1.why]);
 const q2=makeChoice('Từ tiếng Anh của “'+v[1]+'” là gì?',v[0],other.map(x=>x[0]),'Đáp án đúng là '+v[0]+'.');
 placementBank.push([q2.q,q2.o.join(','),q2.a,q2.why]);
}));
const bank=randomize(placementBank).slice(0,Math.min(500,placementBank.length));window.e900BankSize=bank.length;
function newPlacementTest(){tests.splice(0,tests.length,...randomize(bank).slice(0,25));ti=0;testAnswers=[];test()}
resetTest=newPlacementTest;
document.querySelector('#test .lead').textContent='Ngân hàng '+bank.length+' câu từ A0 đến C2; mỗi lượt chọn ngẫu nhiên 25 câu và trộn đáp án.';
newPlacementTest();
})();