(()=>{
const KEY='e900-v2',read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}},write=s=>localStorage.setItem(KEY,JSON.stringify(s));
let state=read();if(!state.profiles)state.profiles=[{id:'learner-1',name:'Học viên 1',created:Date.now()}];if(!state.active)state.active=state.profiles[0].id;if(!state.data)state.data={};if(!state.data[state.active])state.data[state.active]={done:typeof done!=='undefined'?done:[],mistakes:[],xp:0,lastStudy:null};write(state);
const pdata=()=>state.data[state.active];
const section=(id,eyebrow,title,body)=>'<section id="'+id+'" class="view wrap"><span class="eyebrow">'+eyebrow+'</span><h1>'+title+'</h1>'+body+'</section>';
document.querySelector('nav').insertAdjacentHTML('beforeend','<button data-view="review">Ôn lỗi sai</button><button data-view="skills">4 kỹ năng</button><button data-view="profiles">Hồ sơ</button><button data-view="admin">Quản trị</button>');
document.querySelector('main').insertAdjacentHTML('beforeend',
 section('review','HỌC THÍCH ỨNG','Ôn lỗi sai đúng thời điểm','<p class="lead">Câu sai được lưu và lên lịch ôn theo chu kỳ 1–3–7–14 ngày.</p><div id="reviewStats" class="v2grid"></div><div id="mistakeList"></div>')+
 section('skills','LISTENING · SPEAKING · READING · WRITING','Phòng luyện bốn kỹ năng','<div class="skillGrid"><article class="skillPanel"><span class="pill">LISTENING</span><h2>Nghe và chọn nghĩa</h2><div id="listeningBox"></div></article><article class="skillPanel"><span class="pill">SPEAKING</span><h2>Nói theo mẫu</h2><div id="speakingBox"></div></article><article class="skillPanel"><span class="pill">READING</span><h2>Đọc hiểu ngắn</h2><div id="readingBox"></div></article><article class="skillPanel"><span class="pill">WRITING</span><h2>Viết có hướng dẫn</h2><div id="writingBox"></div></article></div>')+
 section('profiles','HỌC VIÊN & PHỤ HUYNH','Hồ sơ học tập trên thiết bị','<p class="lead">Mỗi hồ sơ có tiến độ, lỗi sai và điểm XP riêng. Dữ liệu chỉ lưu trên trình duyệt này.</p><div class="profileBox"><input id="newProfileName" placeholder="Tên học viên"><button class="btn primary" id="addProfile">Thêm hồ sơ</button><div id="profileList" class="profileList"></div></div>')+
 section('admin','CONTENT MANAGEMENT','Quản trị nội dung cục bộ','<p class="lead">Nhập ngân hàng câu hỏi CSV, xuất dữ liệu và chạy kiểm tra hệ thống.</p><div class="adminPanel"><p>Định dạng CSV: <code>question,optionA,optionB,optionC,answer,explanation</code></p><textarea id="csvInput" placeholder="She ___ to school.,go,goes,going,1,She dùng goes."></textarea><div class="adminActions"><button class="btn primary" id="importCsv">Nhập CSV</button><button class="btn soft" id="exportData">Xuất JSON</button><button class="btn soft" id="runTests">Chạy tự kiểm tra</button></div><p id="adminCount"></p><div id="diagnostics" class="diagnostics"></div></div>')
);
document.body.insertAdjacentHTML('beforeend','<div class="offlineBadge">Đang học offline</div>');
function saveProfile(){pdata().done=typeof done!=='undefined'?[...done]:[];pdata().lastStudy=Date.now();write(state)}
function switchProfile(id){saveProfile();state.active=id;if(!state.data[id])state.data[id]={done:[],mistakes:[],xp:0,lastStudy:null};write(state);if(typeof done!=='undefined'){done=[...state.data[id].done];localStorage.setItem('e900',JSON.stringify(done));render()}renderProfiles();renderReview()}
function addMistake(q,chosen,correct,lesson){const d=pdata(),now=Date.now(),old=d.mistakes.find(x=>x.q===q);if(old){old.count++;old.last=now;old.due=now+86400000}else d.mistakes.push({id:Date.now()+'-'+Math.random(),q,chosen,correct,lesson,count:1,stage:0,last:now,due:now});d.xp=Math.max(0,(d.xp||0)-1);write(state);renderReview()}
if(window.expandedAnswer){const base=window.expandedAnswer;window.expandedAnswer=(el,i)=>{base(el,i);if(el.classList.contains('wrong')){const q=document.querySelector('.quiz h2')?.textContent||'',correct=document.querySelector('.quiz .correct')?.textContent||'';addMistake(q,el.textContent,correct,current?.[3]||'Bài học')}}}
const basePick=window.pickTest||pickTest;window.pickTest=function(i){basePick(i);const selected=document.querySelectorAll('#testBox .options button')[i];if(selected?.classList.contains('wrong'))addMistake(document.querySelector('#testBox h2')?.textContent||'',selected.textContent,document.querySelector('#testBox .correct')?.textContent||'','Kiểm tra đầu vào')};
function renderReview(){const m=pdata().mistakes||[],now=Date.now(),due=m.filter(x=>x.due<=now);document.getElementById('reviewStats').innerHTML='<article class="v2card"><span class="v2stat">'+m.length+'</span><h3>Lỗi đã lưu</h3></article><article class="v2card"><span class="v2stat">'+due.length+'</span><h3>Đến hạn ôn</h3></article><article class="v2card"><span class="v2stat">'+(pdata().xp||0)+'</span><h3>Điểm XP</h3></article>';document.getElementById('mistakeList').innerHTML=m.length?m.sort((a,b)=>a.due-b.due).map(x=>'<article class="mistake '+(x.due<=now?'due':'')+'"><span class="pill">'+x.lesson+'</span><h3>'+x.q+'</h3><p><b>Bạn chọn:</b> '+x.chosen+'</p><p><b>Đáp án:</b> '+x.correct+'</p><p>Sai '+x.count+' lần · '+(x.due<=now?'Đến hạn ôn':'Ôn lại '+new Date(x.due).toLocaleDateString('vi-VN'))+'</p><button class="btn primary" onclick="reviewDone(&quot;'+x.id+'&quot;)">Đã ôn và hiểu</button></article>').join(''):'<div class="v2card"><h3>Chưa có lỗi sai 🎉</h3><p>Hãy làm bài tập; các câu sai sẽ tự xuất hiện tại đây.</p></div>'}
window.reviewDone=id=>{const x=pdata().mistakes.find(m=>m.id===id);if(!x)return;x.stage=Math.min((x.stage||0)+1,3);x.due=Date.now()+[1,3,7,14][x.stage]*86400000;pdata().xp=(pdata().xp||0)+5;write(state);renderReview()};
function allWords(){return lessons.flatMap(l=>l[5].map(w=>{const p=w.split('|');return{en:p[0],vi:p[1],lesson:l[3]}}))}
let listenItem=null;window.newListening=()=>{const words=allWords(),item=words[Math.floor(Math.random()*words.length)],wrong=words.filter(x=>x.vi!==item.vi).sort(()=>Math.random()-.5).slice(0,2),opts=[item,...wrong].sort(()=>Math.random()-.5);listenItem=item;document.getElementById('listeningBox').innerHTML='<p class="prompt">Nhấn nghe, sau đó chọn nghĩa đúng.</p><button class="btn primary" onclick="speak(&quot;'+item.en+'&quot;)">🔊 Nghe từ</button><div class="options">'+opts.map(x=>'<button onclick="checkListening(this,&quot;'+x.vi+'&quot;)">'+x.vi+'</button>').join('')+'</div><div id="listenFeedback"></div>'};window.checkListening=(el,v)=>{document.querySelectorAll('#listeningBox .options button').forEach(b=>b.disabled=true);document.getElementById('listenFeedback').innerHTML='<div class="result">'+(v===listenItem.vi?'✓ Chính xác':'✕ Đáp án: '+listenItem.vi)+'<br><button class="btn primary" onclick="newListening()">Câu mới</button></div>';if(v!==listenItem.vi)addMistake('Nghe từ: '+listenItem.en,v,listenItem.vi,'Listening')};
const speakTargets=['I practise English every day.','From my perspective, learning takes time.','The results indicate a significant change.'];let speakTarget=speakTargets[0];window.newSpeaking=()=>{speakTarget=speakTargets[Math.floor(Math.random()*speakTargets.length)];document.getElementById('speakingBox').innerHTML='<p class="prompt">'+speakTarget+'</p><button class="btn primary" onclick="startSpeaking()">🎙️ Bắt đầu nói</button><button class="btn soft" onclick="speak(&quot;'+speakTarget+'&quot;)">🔊 Nghe mẫu</button><div id="speakResult"></div>'};window.startSpeaking=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){document.getElementById('speakResult').innerHTML='<div class="result">Trình duyệt chưa hỗ trợ nhận dạng giọng nói. Hãy nghe mẫu, tự ghi âm bằng thiết bị và so sánh.</div>';return}const r=new SR();r.lang='en-US';r.onresult=e=>{const said=e.results[0][0].transcript,score=Math.round(similarity(said,speakTarget)*100);document.getElementById('speakResult').innerHTML='<div class="result"><b>Bạn nói:</b> '+said+'<br><b>Độ khớp:</b> '+score+'%</div>'};r.start()};
function similarity(a,b){const A=a.toLowerCase().replace(/[^a-z ]/g,'').split(' '),B=b.toLowerCase().replace(/[^a-z ]/g,'').split(' ');return B.filter(x=>A.includes(x)).length/B.length}
const passages=[{t:'Linh studies English for twenty minutes every morning. She reviews old words before learning new ones. On weekends, she watches short videos in English.',q:'Linh làm gì trước khi học từ mới?',a:'Ôn lại từ cũ',o:['Ôn lại từ cũ','Viết bài luận','Đi ngủ']},{t:'Urban gardens can provide fresh food and make neighbourhoods greener. They also give residents a place to meet and work together.',q:'Một lợi ích của vườn đô thị là gì?',a:'Tạo thực phẩm tươi',o:['Tạo thực phẩm tươi','Tăng giao thông','Giảm cộng đồng']}];window.newReading=()=>{const p=passages[Math.floor(Math.random()*passages.length)];document.getElementById('readingBox').innerHTML='<p class="prompt">'+p.t+'</p><h3>'+p.q+'</h3><div class="options">'+p.o.sort(()=>Math.random()-.5).map(x=>'<button onclick="this.parentElement.nextElementSibling.innerHTML=&quot;<div class=result>'+(x===p.a?'✓ Chính xác':'✕ Đáp án: '+p.a)+'</div>&quot;">'+x+'</button>').join('')+'</div><div></div><button class="btn soft" onclick="newReading()">Đoạn mới</button>'};
const writingPrompts=['Write 80–120 words about a habit that helps you learn.','Do you agree that students should use technology in class? Write 120–150 words.','Describe a chart trend using an introduction and an overview.'];window.newWriting=()=>{const p=writingPrompts[Math.floor(Math.random()*writingPrompts.length)];document.getElementById('writingBox').innerHTML='<p class="prompt">'+p+'</p><textarea id="writingText" placeholder="Write here..."></textarea><p><span id="wordCount" class="wordCount">0</span> words</p><div class="checklist"><label><input type="checkbox"> Có câu chủ đề/lập trường</label><label><input type="checkbox"> Có giải thích hoặc ví dụ</label><label><input type="checkbox"> Đã kiểm tra ngữ pháp</label></div><button class="btn primary" onclick="saveWriting()">Lưu bài viết</button><button class="btn soft" onclick="newWriting()">Đề khác</button>';document.getElementById('writingText').oninput=e=>document.getElementById('wordCount').textContent=e.target.value.trim()?e.target.value.trim().split(/\s+/).length:0};window.saveWriting=()=>{const v=document.getElementById('writingText').value;(pdata().writing||(pdata().writing=[])).push({text:v,date:Date.now()});pdata().xp=(pdata().xp||0)+10;write(state);alert('Đã lưu bài viết trên thiết bị.')};
function renderProfiles(){document.getElementById('profileList').innerHTML=state.profiles.map(p=>{const d=state.data[p.id]||{done:[],mistakes:[]};return '<div class="profileRow '+(p.id===state.active?'activeProfile':'')+'"><div><b>'+p.name+'</b><br><small>'+(d.done||[]).length+' bài · '+(d.mistakes||[]).length+' lỗi · '+(d.xp||0)+' XP</small></div><button class="btn '+(p.id===state.active?'soft':'primary')+'" onclick="selectProfile(&quot;'+p.id+'&quot;)">'+(p.id===state.active?'Đang dùng':'Chuyển hồ sơ')+'</button></div>'}).join('')};window.selectProfile=switchProfile;document.getElementById('addProfile').onclick=()=>{const name=document.getElementById('newProfileName').value.trim();if(!name)return;const id='p-'+Date.now();state.profiles.push({id,name,created:Date.now()});state.data[id]={done:[],mistakes:[],xp:0,lastStudy:null};write(state);document.getElementById('newProfileName').value='';renderProfiles()};
function custom(){try{return JSON.parse(localStorage.getItem('e900-custom')||'[]')}catch(e){return[]}}function updateAdmin(){document.getElementById('adminCount').textContent='Nội dung tùy chỉnh trên thiết bị: '+custom().length+' câu.'}document.getElementById('importCsv').onclick=()=>{const lines=document.getElementById('csvInput').value.trim().split(/\r?\n/),items=custom();lines.forEach(line=>{const c=line.split(',');if(c.length>=6)items.push({q:c[0],options:c.slice(1,4),answer:Number(c[4]),explain:c.slice(5).join(',')})});localStorage.setItem('e900-custom',JSON.stringify(items));updateAdmin();alert('Đã nhập '+lines.length+' dòng.')};document.getElementById('exportData').onclick=()=>{saveProfile();const blob=new Blob([JSON.stringify({state,custom:custom()},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='english-900-backup.json';a.click();URL.revokeObjectURL(a.href)};document.getElementById('runTests').onclick=()=>{const checks=[['Có ít nhất 48 bài',lessons.length>=48],['Ngân hàng kiểm tra ≥100 câu',(window.e900BankSize||0)>=100],['LocalStorage hoạt động',(()=>{try{localStorage.setItem('_t','1');localStorage.removeItem('_t');return true}catch(e){return false}})()],['Speech synthesis',('speechSynthesis'in window)],['Service Worker',('serviceWorker'in navigator)]];document.getElementById('diagnostics').innerHTML=checks.map(x=>'<div class="'+(x[1]?'pass':'fail')+'">'+(x[1]?'✓ ':'✕ ')+x[0]+'</div>').join('')};
window.addEventListener('online',()=>document.body.classList.remove('offline'));window.addEventListener('offline',()=>document.body.classList.add('offline'));if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
newListening();newSpeaking();newReading();newWriting();renderProfiles();renderReview();updateAdmin();saveProfile();
})();